### ISSUE TITLE
启动报错 Parsing error loading recipe tofucraft:mineral_soymilk

### ISSUE THREAD

**Issue by Alceatraz** [0999312/TofuCraftReload#87]
## 版本
git-CatServerAsync-1.12.2-99dcf0c (MC: 1.12.2)
API version 1.12.2-R0.1-SNAPSHOT
Forge version 14.23.5.2847
TofuCraftReload 0.1.0.5.1（只有一个）
## 问题描述
1.  放进mods
2. 开服
3. 启动时会抛出一个异常
4. 服务器可正常启动 具体影响还未发现

[20:24:42] [Server thread/ERROR] [FML]: Parsing error loading recipe tofucraft:mineral_soymilk
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Expected name at line 19 column 6 path $.key.T.item
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:494) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:720) ~[CraftingHelper.class:git-CatServerAsync-1.12.2-99dcf0c]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) ~[CraftingHelper.class:git-CatServerAsync-1.12.2-99dcf0c]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:688) ~[CraftingHelper.class:git-CatServerAsync-1.12.2-99dcf0c]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_232]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:633) [CraftingHelper.class:git-CatServerAsync-1.12.2-99dcf0c]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747) [Loader.class:git-CatServerAsync-1.12.2-99dcf0c]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) [FMLServerHandler.class:git-CatServerAsync-1.12.2-99dcf0c]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:340) [FMLCommonHandler.class:git-CatServerAsync-1.12.2-99dcf0c]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:276) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 19 column 6 path $.key.T.item
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:505) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[JsonReader.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[TypeAdapters$35$1.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
	... 12 more

**Comment by Alceatraz** [comment]
又出现了另一个异常，但是依然正常启动正常进入游戏

[21:28:45] [Server thread/ERROR]: Parsing error loading recipe touhou_little_maid:memorizable_gensokyo
com.google.gson.JsonSyntaxException: Unknown item 'patchouli:guide_book'
        at net.minecraftforge.common.crafting.CraftingHelper.getItemStack(CraftingHelper.java:214) ~[CraftingHelper.class:git-CatServerAsync-1.12.2-99dcf0c]
        at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$15(CraftingHelper.java:538) ~[CraftingHelper.class:git-CatServerAsync-1.12.2-99dcf0c]
        at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:416) ~[CraftingHelper.class:git-CatServerAsync-1.12.2-99dcf0c]
        at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:723) ~[CraftingHelper.class:git-CatServerAsync-1.12.2-99dcf0c]
        at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) ~[CraftingHelper.class:git-CatServerAsync-1.12.2-99dcf0c]
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:688) ~[CraftingHelper.class:git-CatServerAsync-1.12.2-99dcf0c]
        at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_232]
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:633) [CraftingHelper.class:git-CatServerAsync-1.12.2-99dcf0c]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747) [Loader.class:git-CatServerAsync-1.12.2-99dcf0c]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) [FMLServerHandler.class:git-CatServerAsync-1.12.2-99dcf0c]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:340) [FMLCommonHandler.class:git-CatServerAsync-1.12.2-99dcf0c]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:276) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
